The remaining files
olakunle-exxdee/sm-rd-responsive-design-resume pull request #2
Opened 2021-03-30 17:32 UTC by olakunle-exxdee

these are the remaining files for the projects

2021-03-31 09:02 UTC, bahdcoder requested changes
Overall, amazing work on this project. You've done a ton of great work here. 

About your responsiveness, can you please check how your site looks on extra large screens like TV ?  Tell me what you think about that.

Looking forward to your changes. 

Also, please try spacing out your HTML a little more. The more readable, the better.

2021-03-31 09:18 UTC, olakunle-exxdee commented on index.html
> +  <head>
thanks

2021-03-31 09:19 UTC, olakunle-exxdee commented on index.html
> +  <body>
i will add the changes

2021-03-31 09:24 UTC, olakunle-exxdee commented on style.css
> +:root {
thanks

2021-03-31 09:33 UTC, olakunle-exxdee commented on normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
to be honest, I heard about normalize CSS through you, most times I just reset all the CSS  from  the root  then start my projects, I don't know of any alternatives now but I will research on it

2021-04-01 08:05 UTC, bahdcoder commented on index.html
> +    <div class="bio-container">
Your HTML reads much better right now. Well done. `bio-container -> wrapper -> bio -> bio-content -> heading`

2021-04-09 20:22 UTC, merged